#! /usr/bin/env -S deno run --allow-read --allow-write

const version = (await Deno.readTextFile("./version.txt")).replaceAll("\n", "");
const readmeTemplate = await Deno.readTextFile("./README-template.md");
const prerelease = version.includes("-");

const readmeData = `<!-- DO NOT EDIT THIS FILE!! -->

${readmeTemplate.replace("{{prerelease}}", prerelease ? "- PRERELEASE" : "")}`;

Deno.writeTextFile("./README.md", readmeData, {
  append: false,
  create: true,
});
